#  Interface definition for weather information.

float64 pressure # Atmospheric pressure, in hPa.
float64 temperature # Outdoor temperature, in K.
float64 humidity # Outdoor relative humidity, between 0 and 1.
float64 in_temperature # Indoor temperature, in K.
float64 in_humidity # Indooor relative humidity, between 0 and 1.
float64 wind_speed # Windspeed, in m/sec.
float64 wind_direction # WindDirection, in digrees between 0 and 360.
float64 rain_rate # Rainrate
float64 time # Time the data were taken at.
string id
