bool capture     # If ``True``, the camera is capturing photos.
string savepath     # Save path of photo.
float64 time     # Timestamp.
string id        # Device identifier.
---
bool captured     # If ``True``, the camera finished capture photos.   