name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: CheckCompilable
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      PACKAGE_NAME: necst_msgs
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set-up environment
        uses: ros-tooling/setup-ros@v0.3
      - name: Build interface files
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          target-ros2-distro: humble
          skip-tests: true
      - name: Check all interfaces are built
        run: |
          for __msg in $(ls ./msg); do [ -z $(ros2 interface list | grep necst_msgs/msg/${__msg%.*}) ] || echo "'$__msg' isn't built" && exit 1; done
          for __srv in $(ls ./srv); do [ -z $(ros2 interface list | grep necst_msgs/srv/${__srv%.*}) ] && echo "'$__srv' isn't built" && exit 1; done
