name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: CheckCompilable
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: necst_msgs
      ROS_DISTRO: humble
    container:
      image: ros:${{ env.ROS_DISTRO }}-ros-base
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
