name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src/main
      - name: Build interface files
        run: |
          echo $(ls)
          echo $(ls ros2_ws/src) && :
          echo $(pwd)
          echo $(which ros2)
          echo $(which colcon)
