name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build interface files
        run: |
          echo $(ls -la)
          echo $(pwd)
          echo $(which colcon)
