name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst_msgs
      ROS2_WS: ros2_ws
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.ROS2_WS }}/src/${{ env.PACKAGE_NAME }}
      - name: Set-up environment
        run: |
          cd ${{ env.ROS2_WS }}
      - name: Build interface files
        run: |
          colcon build --packages-select ${{ env.PACKAGE_NAME }}
