name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: CheckCompilable
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    env:
      PACKAGE_NAME: necst_msgs
      ROS_DISTRO: humble
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src/${{ github.repository }}
      - name: Build ROS package
        run: |
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          ( cd ros2_ws && colcon build --symlink-install )
      - name: Check if all interface definitions have been built
        working_directory: ros2_ws/src/${{ github.repository }}
        run: |
          . /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          for __msg in $(ls ./msg); do [ -z $(ros2 interface list | grep necst_msgs/msg/${__msg%.*}) ] || echo "'$__msg' isn't built" && exit 1; done
          for __srv in $(ls ./srv); do [ -z $(ros2 interface list | grep necst_msgs/srv/${__msg%.*}) ] && echo "'$__srv' isn't built" && exit 1; done
      - name: Debug with tmate
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
